### ISSUE TITLE
ZG-group visualizzazione area privata

### ISSUE THREAD

**Issue by XtraGroove** [XtraGroove/DaybyDay#1]
L'area privata deve visualizzare in ordine di data.  Modificato da Pietro

**Comment by PietroBelloPpz** [comment]
Fatto

**Comment by XtraGroove** [comment]
non è vero vedo ancora problemi! òlàgfkj lkfvnlknòd

**Comment by PietroBelloPpz** [comment]
Schiaccia F5

**Comment by XtraGroove** [comment]
òglj kàslkg

**Comment by mirkovedovato-xtragroove** [comment]
Ottiolmo tutto chiuso
